compra/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("conveniencia/", views.Adicionar_produto, name='conveniencia'),
    path("finalizar_compra/", views.Finalizar_compra, name='finalizar_compra'),
    path("excluir_produto/<int:produto_id>/", views.Excluir_produto, name='excluir_produto'),
    path("limpar/", views.Limpar, name='limpar'),
    path("historico/", views.Historico, name='historico'),
    path("verificar_referencia/", views.Verificar_referencia, name='verificar_referencia'),
    path("relatorio_consumo/", views.Relatorio_consumo, name='relatorio_consumo'),
    path("relatorio_geral/", views.Relatorio_geral, name='relatorio_geral'),
    path("add_prod_codigo/", views.Add_prod_codigo, name='add_prod_codigo'),
    path("finalizar_compra_codigo/", views.Finalizar_compra_codigo, name='finalizar_compra_codigo'),
    path("verificar_referencia_codigo/", views.Verificar_referencia_codigo, name='verificar_referencia_codigo'),
]

conveniencia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include("usuarios.urls")),
    path('', include("pagina_inicial.urls")),
    path('colaboradores/', include("colaboradores.urls")),
    path('produtos/', include("produtos.urls")),
    path('compra/', include("compra.urls")),
    path('estoque/', include("estoque.urls")),
]

compra/models.py
from django.db import models
from produtos.models import Produto
from colaboradores.models import Colaborador
from datetime import date, datetime

class Compra(models.Model):
    data = models.DateTimeField()
    valor_total = models.FloatField(default=0)
    colaborador = models.ForeignKey(Colaborador, on_delete=models.CASCADE, null=True)
    produtos = models.ManyToManyField(Produto, through='Item_Compra')

    def __str__(self):
        return f"Compra {self.id}"
    
class Item_Compra(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(default=1)
    preco= models.FloatField(null=True)

compra/views.py
from django import template
import locale
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from .models import Produto, Compra, Item_Compra, Colaborador
from estoque.models import Estoque
from django.contrib.auth.models import User
from datetime import datetime
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from django.db.models import Sum, Count
from reportlab.lib import colors
from django.contrib import messages
from django.contrib.auth.hashers import check_password
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
import re
from django.db.models import F
from datetime import timedelta, date
from PIL import Image
import cv2 # Lê imagem / entrada de vídeo da câmera
from pyzbar.pyzbar import decode # Biblioteca para decodificar códigos de barras e QR codes

def Add_prod_codigo(request):
    cap = cv2.VideoCapture(0) # Inicializa a captura de vídeo da câmera. O valor 0 indica que será usada a câmera padrão
    cap.set(3, 640) # Define a largura do vídeo 
    cap.set(4, 480) # Define a altura do vídeo
    camera = True
    while camera == True:
        sucess, frame = cap.read() # Captura um quadro (frame) do vídeo da câmera
        cv2.imshow('Testando', frame) # Exibe o frame em uma janela
        cv2.waitKey(1) # Aguarda por 1 milissegundo para que a janela seja atualizada
        if cv2.waitKey(1) & 0xFF == 27:
            cap.release() # Libera o dispositivo de captura (a câmera)
            cv2.destroyAllWindows() # Fecha a janela
            break
        if not sucess:
            cap.release() # Libera o dispositivo de captura (a câmera)
            cv2.destroyAllWindows() # Fecha a janela
        for code in decode(frame): # Decodifica os códigos presentes no frame
            print(code.data.decode('utf-8'))
            codigo = code.data.decode('utf-8') # dado decodificado
            if codigo:
                cap.release() # Libera o dispositivo de captura (a câmera)
                cv2.destroyAllWindows() # Fecha a janela
                produto_codigo_barras = Produto.objects.filter(
                codigo_barras=codigo)
                if not produto_codigo_barras:
                    produtos_adicionados = request.session.get('produtos', [])
                    valor_total = request.session.get('valor_total', 0)
                    messages.error(request, 'Código de barras inválido!',
                                extra_tags='erro_inativo')
                    url = reverse('conveniencia')
                    return redirect(url)
                produto = get_object_or_404(Produto, codigo_barras=codigo)
                if not produto.ativo:
                    messages.error(request, 'Produto está inativo!',
                                extra_tags='erro_inativo')
                    url = reverse('conveniencia')
                    return redirect(url)

                if 'produtos' not in request.session:   # Cria a instância da compra se ainda não existir na sessão
                    request.session['produtos'] = []
                    request.session['valor_total'] = 0
                    request.session['itens'] = 0

                # Verifica se o produto já foi adicionado anteriormente
                produtos = request.session['produtos']
                produto_existente = None
                for produto_data in produtos:
                    if str(produto_data['codigo_barras']) == str(codigo):
                        produto_existente = produto_data
                        break
                estoque = get_object_or_404(Estoque, produtos=produto)
                if estoque.quantidade <= 0:
                    messages.error(request, 'Estoque indisponível!',
                                extra_tags='erro_inativo')
                    url = reverse('conveniencia')
                    return redirect(url)

                if produto_existente:
                    # Incrementa a quantidade do produto existente
                    produto_existente['quantidade'] += 1
                    produto_existente['preco_total'] = produto_existente['preco'] * \
                        produto_existente['quantidade']

                    if estoque.quantidade < produto_existente['quantidade']:
                        messages.error(request, 'Estoque indisponível!',
                                    extra_tags='erro_inativo')
                        url = reverse('conveniencia')
                        return redirect(url)
                else:                                 # Caso o produto ainda não tenha sido adicionado, cria um novo registro na lista de produtos
                    contador = len(produtos) + 1      # Atribui um identificador único
                    preco = f"{produto.preco:.2f}".replace('.', ',')
                    produto_data = {
                        'id': contador,
                        'nome': produto.nome,
                        'codigo_barras': produto.codigo_barras,
                        'preco': preco,
                        'quantidade': 1,
                        'preco_total': produto.preco
                    }
                    produtos.append(produto_data)

                # Atualiza o valor total da compra na sessão
                valor_total = request.session['valor_total']
                valor_total += produto.preco
                request.session['valor_total'] = valor_total

                itens = request.session['itens']
                itens += 1
                request.session['itens'] = itens

                return redirect('conveniencia')

            # Obtém a lista de produtos adicionados na sessão
            produtos_adicionados = request.session.get('produtos', [])
            # Obtém o valor total da compra na sessão
            valor_total = request.session.get('valor_total', 0)
            valor_total = f"{valor_total:.2f}".replace('.', ',')
            itens = request.session.get('itens', 0)
            # Renderiza a página com os produtos adicionados e o valor total
            return render(request, 'compra/conveniencia.html', {'produtos_adicionados': produtos_adicionados, 'valor_total': valor_total, 'itens': itens})
    return redirect('conveniencia')

def Finalizar_compra_codigo(request):
    cap = cv2.VideoCapture(0)
    cap.set(3, 640)
    cap.set(4, 480)
    camera = True
    itens = request.session['itens']
    while camera == True:
        sucess, frame = cap.read()
        cv2.imshow('Testando', frame)
        cv2.waitKey(1)
        if cv2.waitKey(1) & 0xFF == 27:
            cap.release() # Libera o dispositivo de captura (a câmera)
            cv2.destroyAllWindows() # Fecha a janela
            break
        for code in decode(frame):
            codigo = code.data.decode('utf-8')
            if codigo:
                cap.release()
                cv2.destroyAllWindows()
                produtos_adicionados = request.session.get('produtos', [])
                if produtos_adicionados == []:
                    messages.error(request, 'Carrinho vazio! Por favor, adicione um produto para realizar a compra',
                            extra_tags='erro_inativo')
                    url = reverse('conveniencia')
                    return redirect(url)
                valor_total = request.session.get('valor_total', 0)
                valor_total = float(valor_total)
                quantidade = request.session.get('quantidade', 0)
                colaborador = Colaborador.objects.filter(codigo=codigo).first()
                if colaborador:
                    if colaborador.ativo:
                        if colaborador.ativo:
                            if valor_total > 0:

                                # Cria a nova compra e adiciona os produtos
                                compra = Compra.objects.create(
                                    data=datetime.now(), valor_total=valor_total, colaborador=colaborador)
                                data = datetime.now().strftime('%d-%m-%Y %H:%M:%S')
                                for produto_data in produtos_adicionados:
                                    produto = get_object_or_404(
                                        Produto, codigo_barras=produto_data['codigo_barras'])
                                    quantidade = produto_data['quantidade']
                                    preco = produto.preco
                                    item_compra = Item_Compra.objects.create(
                                        compra=compra, produto=produto, preco=preco, quantidade=quantidade)
                                    # Adiciona o produto à relação ManyToMany
                                    compra.produtos.add(produto)
                                # Limpa a lista de produtos na sessão
                                request.session['produtos'] = []
                                # Reseta o valor total da compra na sessão
                                request.session['valor_total'] = 0
                                # Reseta os itens na sessão
                                request.session['itens'] = 0
                                # Atualiza a quantidade no estoque
                                if not produto.tipo == 'Ingresso' and not produto.tipo == 'Camiseta':
                                    estoque = Estoque.objects.get(produtos=produto)
                                    estoque.quantidade = F('quantidade') - quantidade
                                    estoque.save()
                                compra.save()
                                email_mark = ''
                                email_rh = ''
                                user = User.objects.all()
                                for usuario_gestao in user:
                                    if usuario_gestao.username == 'marketing':

templates/compra/conveniencia.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="imagex/png" href="{% static 'imagens/logo.ico' %}">
  <link rel="stylesheet" href="{% static 'compra/conveniencia.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>Conveniência</title>
</head>

<body>
  <form class="form-modal" method="post" action="{% url 'finalizar_compra' %}">
    {% csrf_token %}
    <div class="modal fade" id="enviarLoginModal" tabindex="-1" role="dialog" aria-labelledby="enviarLoginModalLabel"
      aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title3" id="enviarLoginModalLabel">Confirmação de Colaborador</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <br>
            <div class="form-group input-ref">
              <input type="text" class="form-control login" id="login" value="{{request.POST.login}}" name="login"
                autocomplete="off" required>
              <span>Login</span>
            </div>
            <div class="erro" id="erro">
              {{ erro }}
            </div>
            <br>
            <div class="form-group input-ref">
              <input type="password" class="form-control senhaConf" id="senha" name="senha" autocomplete="off" required>
              <span>Senha</span>
            </div>
            <span class="input-group-text-senha">
              <i class="fas fa-eye" id="togglePasswordC"></i>
            </span>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <button class="btn btn-primary btn-ok-modal">OK</button>
          </div>
        </div>
      </div>
    </div>
  </form>

  <form class="form-modal" method="post" action="{% url 'verificar_referencia' %}">
    {% csrf_token %}
    <div class="modal fade" id="enviarLoginRefModal" tabindex="-1" role="dialog"
      aria-labelledby="enviarLoginRefModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title1" id="enviarLoginRefModalLabel">Verificar Referência</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <br>
            <div class="error-message" id="error-message"></div>
            <div class="form-group input-ref">
              <input type="text" class="form-control login" id="loginn" name="login" autocomplete="off" required>
              <span>Login</span>
            </div>
            <div class="erroo" id="erroo">
              {{ erro }}
            </div>
            <br>
            <div class="form-group input-ref">
              <input type="password" class="form-control senhaRef" id="senhaa" name="senha" autocomplete="off" required>
              <span>Senha</span>
            </div>
            <span class="input-group-text-senha">
              <i class="fas fa-eye" id="togglePasswordR"></i>
            </span>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <button class="btn btn-primary btn-ok-modal">OK</button>
          </div>
        </div>
      </div>
    </div>
  </form>

  <div class="modal fade" id="enviarReferenciaModal" tabindex="-1" role="dialog" aria-labelledby="enviarReferenciaModal"
    aria-hidden="true">
    <div class="modal-dialog ref align-items-center" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title2" id="enviarReferenciaModalLabel">Gastos: {{colaborador}}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Referência Anterior: R$ {{ gasto_referencia_anterior }}</p>
          <p>Referência Atual: R$ {{ gasto_referencia_atual }}</p>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>

  <form class="form-compra" method="post" action="{% url 'conveniencia' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {% if messages %}
    <div class="messages">
      {% for message in messages %}
      <li{% if message.tags %} id={{message.tags}} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </div>
    {% endif %}
    <img class="imagem" src="{% static 'imagens/logooficial.png' %}">
    <strong class="campo">Inserir produto:</strong>
    <div class="form-group input-cod">
      <input type="text" required class="form-control codigo-barras" id="codigo_barras" maxlength="13" name="codigo_barras"
        autocomplete="off">
      <span>Código de Barras</span>
    </div>
    <button class="btn btn-light botao-add" type="submit"><strong>Adicionar Produto</strong></button>
    <button class="btn btn-light botao-limpar" name="limpar" formnovalidate formaction="{% url 'limpar' %}">
      <strong>Limpar</strong></button>
    <a class="btn btn-light botao-finalizar" data-toggle="modal" data-target="#enviarLoginModal"><strong>Finalizar
        Compra</strong></a>
    <a class="btn btn-light botao-referencia" data-toggle="modal" data-target="#enviarLoginRefModal"><strong>Verificar
        Referência</strong></a>
    <a class="fa fa-qrcode botao-add-codigo" href="{% url 'add_prod_codigo' %}"></a>
    <a class="fa fa-qrcode finalizar-compra-codigo" href="{% url 'finalizar_compra_codigo' %}"></a>
        <a class="fa fa-qrcode botao-referencia-codigo" href="{% url 'verificar_referencia_codigo' %}"></a>
    <div class="lista">
      <table class="table table-hover">
        {% if produtos_adicionados %}
        <strong class="prod_add">Produtos Adicionados</strong>
        <thead class="topo">
          <tr class="topo">
            <th scope="col" class="nome">Nome</th>
            <th scope="col" class="codbarras">Código de Barras</th>
            <th scope="col" class="preco">Preço</th>
            <th scope="col" class="qtd">Quantidade</th>
            <th scope="col" class="exc"></th>
          </tr>
        </thead>
        <ul>
          {% for produto_data in produtos_adicionados %}
          <div class="produtos">
            <tr>
              <td>{{ produto_data.nome }}</td>
              <td>{{ produto_data.codigo_barras }}</td>
              <td class="inpreco">R$ {{ produto_data.preco }}</td>
              <td class="inquantidade">{{ produto_data.quantidade }}</td>
              <td>
                <a href="{% url 'excluir_produto' produto_data.id %}" class="fa fa-minus-square lixeira"
                  aria-hidden="true"></a>
          </div>
          {% endfor %}
        </ul>
      </table>
    </div>
    <div class="valor_total">
      <h5><strong>Valor Total da Compra: R$ {{ valor_total }}</strong></h5>
    </div>
    <div class="itens">
      <h5><strong>Itens: {{itens}}</strong></h5>
      {% endif %}
    </div>
  </form>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"></script>

  <script>
    const codigoBarrasField = document.getElementById("codigo_barras");
    codigoBarrasField.addEventListener("input", function () {
      this.value = this.value.replace(/\D/g, "");
    });

    function hideSuccessMessage(message) {
      var erroInativo = document.getElementById("erro_inativo");
      erroInativo.innerText = message;
      erroInativo.style.display = "block";
      setTimeout(function () {
        erroInativo.style.display = "none";
      }, 4000);
    }
    var erroInativo = document.getElementById("erro_inativo");
    if (erroInativo) {
      var message = erroInativo.innerText;
      hideSuccessMessage(message);
    }

    function finalizar_compra() {
      window.location = "{% url 'finalizar_compra' %}";
    }

    {% if mostrar_ref %}

    $(document).ready(function () {
      $('#enviarReferenciaModal').modal('show');
    });

    setTimeout(function () {
      $('#enviarReferenciaModal').modal('hide');
      loginn.value = ''
      senhaa.value = ''
      window.location = "{% url 'conveniencia' %}"
    }, 8000);

    {% endif %}

    $('#enviarReferenciaModal').on('hidden.bs.modal', function () {
      window.location = "{% url 'conveniencia' %}"
    });


    $('#enviarLoginModal').on('hidden.bs.modal', function () {
      login.value = ''
      senha.value = ''
      erroo.style.display = 'none';
      erro.style.display = 'none';
      var newURL = window.location.protocol + '//' + window.location.host + '/compra/conveniencia';
      window.history.pushState({ path: newURL }, '', newURL);
    });

    $('#enviarLoginRefModal').on('hidden.bs.modal', function () {
      loginn.value = ''
      senhaa.value = ''
      erroo.style.display = 'none';
      erro.style.display = 'none';

      var newURL = window.location.protocol + '//' + window.location.host + '/compra/conveniencia';
      window.history.pushState({ path: newURL }, '', newURL);
    });


    {% if mostrar_cad %}

    $(document).ready(function () {
      $('#enviarLoginModal').modal('show');
      var newURL = window.location.protocol + '//' + window.location.host + '/compra/conveniencia';
      window.history.pushState({ path: newURL }, '', newURL);
    });

    {% endif %}


    const togglePasswordR = document.querySelector('#togglePasswordR');
    const passwordInputR = document.querySelector('.senhaRef');

    togglePasswordR.addEventListener('click', function () {
      const type = passwordInputR.getAttribute('type') === 'password' ? 'text' : 'password';
      passwordInputR.setAttribute('type', type);
      togglePasswordR.classList.toggle('fa-eye-slash');
    });

    const togglePasswordC = document.querySelector('#togglePasswordC');
    const passwordInputC = document.querySelector('.senhaConf');

    togglePasswordC.addEventListener('click', function () {
      const type = passwordInputC.getAttribute('type') === 'password' ? 'text' : 'password';
      passwordInputC.setAttribute('type', type);
      togglePasswordC.classList.toggle('fa-eye-slash');
    });
  </script>

  </script>
</body>

</html>

templates/compra/historico.html
{% extends 'navbar/navbar.html' %}
{% block title %}Index{% endblock %}
{% block head %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'compra/historico.css' %}" />
  <title>Histórico de Compras</title>
</head>

<body>
  <form class="form-visualizacao-historico">
    {% csrf_token %}
    <div class="tela">
      {% if sucesso_cadastro %}
      <div class="success-cadastro-message" id="success-cadastro-message">
        {{ sucesso_cadastro }}
      </div>
      {% endif %}

      <h2 class="titulo"><strong>Lista de Compras</strong></h2>
      <input class="busca filtro-data" type="text" id="data" name="filtro-data" placeholder="Filtrar por Data e Hora">
      <input class="busca filtro-valor" type="text" id="valor" name="filtro-valor"
        placeholder="Filtrar por Valor Total">
      <input class="busca filtro-colab" type="text" id="colab" name="filtro-colab"
        placeholder="Filtrar por Colaborador">
      <input class="busca filtro-prod" type="text" id="prod" name="filtro-prod" placeholder="Filtrar por Produtos">
      <input class="busca filtro-codigo-barras" type="text" id="codigo-barras" name="filtro-codigo-barras"
        placeholder="Filtrar por Código de Barras">
      <input class="busca filtro-qtd" type="text" id="qtd" name="filtro-qtd" placeholder="Filtrar por Quantidade">
      <!-- <div class="filtro">
        <input class="form-control busca" type="text" name="pesquisa" id="pesquisa" placeholder="Filtre por data d-m-a ou d/m/a">
        <button class="btn btn-light btn-buscar" type="submit">Buscar</button>
      </div> -->
      <table class="table table lista">
        <thead>
          <tr>
            <th scope="col">Data</th>
            <th scope="col">Valor total</th>
            <th scope="col">Colaborador</th>
            <th scope="col">Produtos</th>
            <th scope="col">Código de Barras</th>
            <th scope="col">Quantidade</th>
          </tr>
        </thead>
        <tbody>
          {% for compra in compras %}
          <tr>
            <td>{{ compra.data|date:"d-m-Y H:i:s"}}</td>
            <td class="preco">R$ {{ compra.valor_total }}</td>
            <td>{{ compra.colaborador }}</td>
            <td>
              {% for item in compra.item_compra_set.all %}
              {{ item.produto.nome }}
              <br>
              {% endfor %}
            </td>
            <td>
              {% for item in compra.item_compra_set.all %}
              {{ item.produto.codigo_barras }}
              <br>
              {% endfor %}
            </td>
            <td>
              {% for item in compra.item_compra_set.all %}
              {{item.quantidade}}
              <br>
              {% endfor %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </form>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"></script>
  <script>

function formatarPreco() {
      var precoFields = document.getElementsByClassName("preco");

      for (var i = 0; i < precoFields.length; i++) {
        var precoField = precoFields[i];
        var precoValor = precoField.innerText.replace("R$ ", "").replace(",", ".");
        var precoNumerico = parseFloat(precoValor);

        if (!isNaN(precoNumerico)) {
          var precoFormatado = precoNumerico.toLocaleString("pt-BR", {
            style: "currency",
            currency: "BRL",
          });

          precoField.innerText = precoFormatado;
        }
      }
    }

    formatarPreco();

    $(document).ready(function () {
      formatarPreco();
    });

    const nomeField = document.getElementById("colab");
    nomeField.addEventListener("input", function () {
      this.value = this.value.replace(/[0-9!@#$%¨^&*(),.?":{}|<>[\];=_/+\\-]/g, "");
    });

    const prodField = document.getElementById("prod");
    prodField.addEventListener("input", function () {
      this.value = this.value.replace(/[0-9!@#$%¨^&*(),.?":{}|<>[\];=_/+\\-]/g, "");
    });


    $(document).ready(function () {
      // Evento 'input' é acionado quando o usuário digita em um dos campos de filtro
      $('.filtro-data, .filtro-valor, .filtro-colab, .filtro-prod, .filtro-codigo-barras, .filtro-qtd').on('input', function () {
        atualizarListaHistorico();
      });

      function atualizarListaHistorico() {
        // Captura os valores dos campos de filtro
        var filtroData = $('.filtro-data').val().toLowerCase();
        var filtroValor = $('.filtro-valor').val().replace(/[^0-9]/g, ''); // Remove a formatação do CPF
        var filtroColab = $('.filtro-colab').val().toLowerCase();
        var filtroProd = $('.filtro-prod').val().toLowerCase();
        var filtroCodigoBarras = $('.filtro-codigo-barras').val().toLowerCase();
        var filtroQtd = $('.filtro-qtd').val().toLowerCase();

        // Itera sobre cada linha da tabela de colaboradores
        $('.table tbody tr').each(function () {
          // Obtém os valores dos campos em cada linha
          var data = $(this).find('td:nth-child(1)').text().toLowerCase();
          var valor = $(this).find('td:nth-child(2)').text().toLowerCase();
          var colab = $(this).find('td:nth-child(3)').text().toLowerCase();
          var prod = $(this).find('td:nth-child(4)').text().toLowerCase();
          var cod = $(this).find('td:nth-child(5)').text().toLowerCase();
          var qtd = $(this).find('td:nth-child(6)').text().toLowerCase();

          // Verifica se os valores correspondem aos filtros e exibe ou oculta a linha
          if ((filtroData === '' || data.indexOf(filtroData) !== -1) &&
            (filtroValor === '' || valor.indexOf(filtroValor) !== -1) &&
            (filtroColab === '' || colab.indexOf(filtroColab) !== -1) &&
            (filtroProd === '' || prod.indexOf(filtroProd) !== -1) &&
            (filtroCodigoBarras === '' || cod.indexOf(filtroCodigoBarras) !== -1) &&
            (filtroQtd === '' || qtd.indexOf(filtroQtd) !== -1)) {
            $(this).show(); // Exibe a linha se corresponder aos filtros
          } else {
            $(this).hide(); // Oculta a linha se não corresponder aos filtros
          }
        });
      }
    });
  </script>
  {% endblock %}
</body>

</html>