compra/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("conveniencia/", views.Adicionar_produto, name='conveniencia'),
    path("finalizar_compra/", views.Finalizar_compra, name='finalizar_compra'),
    path("excluir_produto/<int:produto_id>/", views.Excluir_produto, name='excluir_produto'),
    path("limpar/", views.Limpar, name='limpar'),
    path("historico/", views.Historico, name='historico'),
    path("verificar_referencia/", views.Verificar_referencia, name='verificar_referencia'),
    path("relatorio_consumo/", views.Relatorio_consumo, name='relatorio_consumo'),
    path("relatorio_geral/", views.Relatorio_geral, name='relatorio_geral'),
    path("add_prod_codigo/", views.Add_prod_codigo, name='add_prod_codigo'),
    path("finalizar_compra_codigo/", views.Finalizar_compra_codigo, name='finalizar_compra_codigo'),
    path("verificar_referencia_codigo/", views.Verificar_referencia_codigo, name='verificar_referencia_codigo'),
]

conveniencia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include("usuarios.urls")),
    path('', include("pagina_inicial.urls")),
    path('colaboradores/', include("colaboradores.urls")),
    path('produtos/', include("produtos.urls")),
    path('compra/', include("compra.urls")),
    path('estoque/', include("estoque.urls")),
]

estoque/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("estoque/", views.Visualizar, name='estoque'),
    path("att_qtd_entrada/<int:estoque_id>/", views.Att_qtd_entrada, name='att_qtd_entrada'),
    path("att_qtd_saida/<int:estoque_id>/", views.Att_qtd_saida, name='att_qtd_saida'),
    path("entrada_estoque/<int:estoque_id>/", views.Entrada_estoque, name='entrada_estoque'),
    path("saida_estoque/<int:estoque_id>/", views.Saida_estoque, name='saida_estoque'),
    path("movimentacao/", views.Movimentacao, name='movimentacao'),
]

estoque/models.py
from django.db import models
from produtos.models import Produto
from django.contrib.auth.models import User

class Estoque(models.Model):
    produtos = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.IntegerField(null=True, default=0)

    def __str__(self):
        return f"Estoque {self.id}"
    
class MovimentacaoEstoque(models.Model):
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE)
    data_hora = models.DateTimeField(null=True, default=0)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    quantidade_alteracao = models.IntegerField(null=True, default=0)

    tipos = (
        ('Entrada', 'Entrada'),
        ('Saída', 'Saída')
    )

    tipo = models.CharField(
            max_length=20, choices=tipos, null=True)

    def __str__(self):
        return f"Estoque {self.id}"
    

estoque/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from produtos.models import Produto
from django.contrib.auth.decorators import login_required
import logging
logger = logging.getLogger()
from django.views.decorators.cache import never_cache
from .models import Estoque, MovimentacaoEstoque
from datetime import datetime
from django.contrib import messages
from django.db.models import F

@never_cache
@login_required(login_url='login')
def Visualizar(request):  
    produto = Produto.objects.all()
    estoque = Estoque.objects.all()
    sucesso_cadastro = request.GET.get('sucesso_cadastro')

    return render(request, "estoque/visualizar.html", {"produtos": produto, 'estoque': estoque, 'sucesso_cadastro': sucesso_cadastro})

@login_required(login_url='login')
def Att_qtd_entrada(request, estoque_id):
    if request.method == 'POST':
        entrada = request.POST.get('entrada')
        estoque = get_object_or_404(Estoque, id=estoque_id)
        estoque.quantidade = estoque.quantidade + int(entrada)
        estoque.save()

        movimentacao = MovimentacaoEstoque()
        movimentacao.estoque = estoque
        movimentacao.data_hora = datetime.now()
        movimentacao.usuario = request.user
        movimentacao.quantidade_alteracao = int(entrada)
        movimentacao.tipo = 'Entrada'
        movimentacao.save()
        url = reverse('estoque')
        messages.success(request,f'Estoque de produto {estoque.produtos.nome} alterado com sucesso!', extra_tags='sucesso_cadastro')
        return redirect(url)

    return redirect('estoque')

@login_required(login_url='login')
def Att_qtd_saida(request, estoque_id):
    if request.method == 'POST':
        saida = request.POST.get('saida')
        estoque = get_object_or_404(Estoque, id=estoque_id)
        if int(saida) > estoque.quantidade:
            messages.error(request, 'Não é possível realizar a movimentação!',
                               extra_tags='erro')
            url = reverse('saida_estoque', args=[estoque_id])
            return redirect(url)
        
        estoque.quantidade = estoque.quantidade - int(saida)
        estoque.save()

        movimentacao = MovimentacaoEstoque()
        movimentacao.estoque = estoque
        movimentacao.data_hora = datetime.now()
        movimentacao.usuario = request.user
        movimentacao.quantidade_alteracao = int(saida)
        movimentacao.tipo = 'Saída'
        movimentacao.save()
        url = reverse('estoque')
        messages.success(request,f'Estoque de produto {estoque.produtos.nome} alterado com sucesso!', extra_tags='sucesso_cadastro')
        return redirect(url)

    return redirect('estoque')


@never_cache
@login_required(login_url='login')
def Acessar(request, produto_id):    # Visualização de edição
    produto = Produto.objects.get(id=produto_id)
    return render(request, 'produtos/acessar.html', {'produto': produto})

@never_cache
@login_required(login_url='login')
def Entrada_estoque(request, estoque_id):  
    estoque = Estoque.objects.get(id=estoque_id)

    return render(request, "estoque/entrada_estoque.html", {'estoque': estoque})

@never_cache
@login_required(login_url='login')
def Saida_estoque(request, estoque_id):  
    estoque = Estoque.objects.get(id=estoque_id)

    return render(request, "estoque/saida_estoque.html", {'estoque': estoque})

@never_cache
@login_required(login_url='login')
def Movimentacao(request):  
    produto = Produto.objects.all()
    estoque = Estoque.objects.all()
    movimentacao = MovimentacaoEstoque.objects.all()

    return render(request, "estoque/movimentacao.html", {'estoque': estoque, 'produto': produto, 'movimentacao': movimentacao})

templates/estoque/entrada_estoque.html
{% extends 'navbar/navbar.html' %}
{% block title %}Index{% endblock %}
{% block head %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'estoque/entrada_estoque.css' %}" />
  <title>Acesso ao Produto</title>
</head>

<body>
  <div class="form">
    <form class="form-acesso-produto"action="{% url 'att_qtd_entrada' estoque.id %}" method="POST">
      {% csrf_token %}
      <img class="robot" src="{% static 'imagens/robot.png' %}">
      {% if messages %}
      <div class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
      </div>
      {% endif %}
      <h2 class="titulo">Entrada de Estoque</h2>
      <i onclick="history.back()" class="fa fa-arrow-left arrow"></i>
      <input type="hidden" value="{{estoque.id}}" name="estoque_id">
      {% if messages %}
      <div class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
      </div>
      {% endif %}
      <div class="form-group input-nome">
        <input type="text" class="form-control nome" id="nome" name="nome" readonly
          value="{{estoque.produtos}}" />
          <p class="nome_label">Nome</p> 
      </div>
      <div class="form-group">
        <input type="text" class="form-control qtd" id="qtd" name="qtd" readonly
          value="{{estoque.quantidade}}" />
          <p class="quantidade_label">Quantidade atual</p>      
      </div>
      <div class="form-group">
        <input type="text" class="form-control entrada" id="entrada" name="entrada" required autocomplete="off"
           />
        <span>Quantidade entrada</span>
      </div>
      <div class="form-group">
        <label for="quantidade-atual">Quantidade atualizada:</label>
        <span id="quantidade-atual"></span>
      </div>
      <button type="submit" class="btn btn-success botao-salvar btn-lg">Salvar</button>
    </form>
  </div>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"></script>
  <script>
    // Obtém referências aos elementos HTML
    var entradaInput = document.getElementById('entrada');
    var quantidadeAtualSpan = document.getElementById('quantidade-atual');
  
    // Adiciona um evento de input ao campo de entrada
    entradaInput.addEventListener('input', function() {
      var quantidadeAtual = parseInt('{{ estoque.quantidade }}'); // Obtém a quantidade atual do produto
      var entrada = parseInt(entradaInput.value); // Obtém a entrada digitada pelo cliente
  
      if (!isNaN(entrada)) {
        var quantidadeAtualizada = quantidadeAtual + entrada; // Calcula a quantidade atualizada
  
        quantidadeAtualSpan.textContent = quantidadeAtualizada; // Atualiza o texto do elemento HTML
      } else {
        quantidadeAtualSpan.textContent = quantidadeAtual; // Mantém a quantidade atual se a entrada for inválida
      }
    });
  
    // Adiciona um evento de 'change' ao campo de entrada
    entradaInput.addEventListener('change', function() {
      if (entradaInput.value === '') {
        quantidadeAtualSpan.textContent = '{{ estoque.quantidade }}'; // Restaura a quantidade atual se o campo de entrada estiver vazio
      }
    });

    const codigoField = document.getElementById("entrada");
    codigoField.addEventListener("input", function () {
      this.value = this.value.replace(/[^0-9]/g, "");
    });
    
  </script>
  
  {% endblock %}
</body>

</html>

templates/estoque/movimentacao.html
{% extends 'navbar/navbar.html' %}
{% block title %}Index{% endblock %}
{% block head %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'estoque/movimentacao.css' %}" />
  <title>Visualização de Movimentações</title>
</head>

<body>
  <form class="form-visualizacao-estoque">
    {% csrf_token %}
    {% if sucesso_cadastro %}
    <div class="success-cadastro-message" id="success-cadastro-message">
      {{ sucesso_cadastro }}
    </div>
    {% endif %}
    <h2 class="titulo"><strong>Movimentações do Estoque</strong></h2>
    <input class="busca filtro-nome" type="text" id="nome" name="filtro-nome" placeholder="Filtrar por Nome">
    <input class="busca filtro-codigo-barras" type="text" id="cod-barras" name="filtro-codigo-barras"
      placeholder="Filtrar por Código de Barras">
    <input class="busca filtro-data-hora" type="text" id="data-hora" name="filtro-data-hora"
      placeholder="Filtrar por Data e Hora">
    <input class="busca filtro-tipo" type="text" id="tipo" name="filtro-tipo"
      placeholder="Filtrar por Tipo de Movimentação">
    <input class="busca filtro-qtd" type="text" id="qtd" name="filtro-qtd" placeholder="Filtrar por Quantidade">
    <input class="busca filtro-usuario" type="text" name="filtro-usuario" placeholder="Filtrar por Usuário">
    <table class="table table-hover lista">
      <thead>
        <tr>
          <th class="nome" scope="col">Nome</th>
          <th class="codbarras" scope="col">Código de Barras</th>
          <th scope="col" class="data_hora">Data e hora</th>
          <th scope="col" class="tipo">Tipo de Movimentação</th>
          <th scope="col" class="quantidade">Quantidade</th>
          <th scope="col" class="usuario">Usuário</th>
        </tr>
      </thead>
      <tbody>
        {% for movimentacao in movimentacao %}
        <tr>
          <td>{{ movimentacao.estoque.produtos}}</td>
          <td class="cod">{{ movimentacao.estoque.produtos.codigo_barras }}</td>
          <td class="dataa">{{ movimentacao.data_hora|date:"d-m-Y H:i:s"}}</td>
          <td>{{ movimentacao.tipo }}</td>
          <td class="qtd">{{ movimentacao.quantidade_alteracao }}</td>
          <td>{{ movimentacao.usuario }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </form>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"></script>
  <script>

    const nomeField = document.getElementById("nome");
    nomeField.addEventListener("input", function () {
      this.value = this.value.replace(/[0-9!@#$%¨^&*(),.?":{}|<>[\];=_/+\\-]/g, "");
    });

    const codigoField = document.getElementById("cod-barras");
    codigoField.addEventListener("input", function () {
      this.value = this.value.replace(/[^0-9]/g, "");
    });

    const qtdField = document.getElementById("qtd");
    qtdField.addEventListener("input", function () {
      this.value = this.value.replace(/[^0-9]/g, "");
    });

    const tipoField = document.getElementById("tipo");
    tipoField.addEventListener("input", function () {
      this.value = this.value.replace(/[0-9´~'!@#$%¨^&*(),.?":{}|<>[\];=_/+\\-]/g, "");
    });

    const dataField = document.getElementById("data-hora");
    dataField.addEventListener("input", function () {
      this.value = this.value.replace(/[^0-9: -]/g, "");
    });

    $(document).ready(function () {
      // Evento 'input' é acionado quando o usuário digita em um dos campos de filtro
      $('.filtro-nome, .filtro-codigo-barras, .filtro-data-hora, .filtro-tipo, .filtro-qtd, .filtro-usuario').on('input', function () {
        // Chamada para a função de atualização da lista de colaboradores
        atualizarListaColaboradores();
      });

      function atualizarListaColaboradores() {
        // Captura os valores dos campos de filtro
        var filtroNome = $('.filtro-nome').val().toLowerCase();
        var filtroCodigoBarras = $('.filtro-codigo-barras').val().toLowerCase();
        var filtroDataHora = $('.filtro-data-hora').val().toLowerCase();
        var filtroTipo = $('.filtro-tipo').val().toLowerCase();
        var filtroQuantidade = $('.filtro-qtd').val().toLowerCase();
        var filtroUsuario = $('.filtro-usuario').val().toLowerCase();

        // Itera sobre cada linha da tabela de colaboradores
        $('.table tbody tr').each(function () {
          // Obtém os valores dos campos em cada linha
          var nome = $(this).find('td:nth-child(1)').text().toLowerCase();
          var cod = $(this).find('td:nth-child(2)').text().toLowerCase();
          var datahora = $(this).find('td:nth-child(3)').text().toLowerCase();
          var tipo = $(this).find('td:nth-child(4)').text().toLowerCase();
          var qtd = $(this).find('td:nth-child(5)').text().toLowerCase();
          var usuario = $(this).find('td:nth-child(6)').text().toLowerCase();

          // Verifica se os valores correspondem aos filtros e exibe ou oculta a linha
          if ((filtroNome === '' || nome.indexOf(filtroNome) !== -1) &&
            (filtroCodigoBarras === '' || cod.indexOf(filtroCodigoBarras) !== -1) &&
            (filtroDataHora === '' || datahora.indexOf(filtroDataHora) !== -1) &&
            (filtroTipo === '' || tipo.indexOf(filtroTipo) !== -1) &&
            (filtroQuantidade === '' || qtd.indexOf(filtroQuantidade) !== -1) &&
            (filtroUsuario === '' || usuario.indexOf(filtroUsuario) !== -1)) {
            $(this).show(); // Exibe a linha se corresponder aos filtros
          } else {
            $(this).hide(); // Oculta a linha se não corresponder aos filtros
          }
        });
      }
    });
  </script>
  {% endblock %}
</body>

</html>

templates/estoque/saida_estoque.html
{% extends 'navbar/navbar.html' %}
{% block title %}Index{% endblock %}
{% block head %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'estoque/saida_estoque.css' %}" />
  <title>Acesso ao Produto</title>
</head>

<body>
  <div class="form">
    <form class="form-acesso-produto" action="{% url 'att_qtd_saida' estoque.id %}" method="POST">
      {% csrf_token %}
      <img class="robot" src="{% static 'imagens/robot.png' %}">
      {% if messages %}
      <div class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
      </div>
      {% endif %}
      <h2 class="titulo">Saída de Estoque</h2>
      <i onclick="history.back()" class="fa fa-arrow-left arrow"></i>
      <input type="hidden" value="{{estoque.id}}" name="estoque_id">
      {% if messages %}
      <div class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
      </div>
      {% endif %}
      <div class="form-group input-nome">
        <input type="text" class="form-control nome" id="nome" name="nome" readonly value="{{estoque.produtos}}" />
        <p class="nome_label">Nome</p> 
      </div>
      <div class="form-group">
        <input type="text" class="form-control qtd" id="qtd" name="qtd" readonly value="{{estoque.quantidade}}" />
        <p class="quantidade_label">Quantidade atual</p>      
      </div>
      <div class="form-group">
        <input type="text" class="form-control saida" id="saida" name="saida" required autocomplete="off" />
        <span>Saída</span>
      </div>
      <div class="form-group">
        <label for="quantidade-atual">Quantidade atualizada:</label>
        <span id="quantidade-atual"></span>
      </div>
      <button type="submit" class="btn btn-success botao-salvar btn-lg">Salvar</button>
    </form>
  </div>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"></script>
  <script>
    // Obtém referências aos elementos HTML
    var saidaInput = document.getElementById('saida');
    var quantidadeAtualSpan = document.getElementById('quantidade-atual');
  
    // Adiciona um evento de input ao campo de saída
    saidaInput.addEventListener('input', function () {
      var quantidadeAtual = parseInt('{{ estoque.quantidade }}'); // Obtém a quantidade atual do produto
      var saida = parseInt(saidaInput.value); // Obtém a saída digitada pelo cliente
  
      if (!isNaN(saida)) {
        var quantidadeAtualizada = quantidadeAtual - saida; // Calcula a quantidade atualizada
  
        quantidadeAtualSpan.textContent = quantidadeAtualizada; // Atualiza o texto do elemento HTML
      } else {
        quantidadeAtualSpan.textContent = quantidadeAtual; // Mantém a quantidade atual se a saída for inválida
      }
    });
  
    // Adiciona um evento de 'change' ao campo de saída
    saidaInput.addEventListener('change', function () {
      if (saidaInput.value === '') {
        quantidadeAtualSpan.textContent = '{{ estoque.quantidade }}'; // Restaura a quantidade atual se o campo de saída estiver vazio
      }
    });

    const codigoField = document.getElementById("saida");
    codigoField.addEventListener("input", function () {
      this.value = this.value.replace(/[^0-9]/g, "");
    });

  </script>
  
  {% endblock %}
</body>

</html>

templates/estoque/visualizar.html
{% extends 'navbar/navbar.html' %}
{% block title %}Index{% endblock %}
{% block head %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'estoque/visualizar.css' %}" />
  <title>Visualização de Estoque</title>
</head>

<body>
  <form class="form-visualizacao-estoque">
    {% csrf_token %}
    {% if messages %}
    <div class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="titulo"><strong>Estoque</strong></h2>
    <input class="busca filtro-nome" type="text" id="nome" name="filtro-nome" placeholder="Filtrar por Nome">
    <input class="busca filtro-codigo-barras" type="text" id="codigo-barras" name="filtro-codigo-barras"
      placeholder="Filtrar por Código de Barras">
    <input class="busca filtro-classif" type="text" id="classif" name="filtro-classif"
      placeholder="Filtrar por Classificação">
    <input class="busca filtro-qtd" type="text" id="qtd" name="filtro-qtd" placeholder="Filtrar por Quantidade">
    <table class="table table-hover lista">
      <thead>
        <tr>
          <th class="nome" scope="col">Nome</th>
          <th scope="col" class="quantidade">Quantidade</th>
          <th class="codbarras" scope="col">Código de Barras</th>
          <th scope="col" class="classificacao">Classificação</th>
          <th scope="col" class="opc">Movimentação</th>
        </tr>
      </thead>
      <tbody>
        {% for produto in produtos %}
        {% if produto.ativo %}
        {% for estoque in produto.estoque_set.all %}
        <tr>
          <td>{{ produto.nome }}</td>
          <td id="qtd" name="qtd" class="quantidade-atual">
            {{ estoque.quantidade }}
          </td>
          <td class="cod">{{ produto.codigo_barras }}</td>
          <td>{{ produto.tipo }}</td>
          <input type="hidden" value="{{ estoque.id }}" name="id_estoque_id">
          <td class="botoes">
            <a href="{% url 'entrada_estoque' estoque.id %}" class="btn btn entrada">Entrada</a>
            <a href="{% url 'saida_estoque' estoque.id %}" class="btn btn saida">Saída</a>
          </td>
        </tr>
        {% endfor %}
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </form>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>

    const messages = window.document.querySelector('.messages');

    setTimeout(() => {
      messages.style.display = 'none';
    }, 5000);

    const nomeField = document.getElementById("nome");
    nomeField.addEventListener("input", function () {
      this.value = this.value.replace(/[0-9!@#$%¨^&*(),.?":{}|<>[\];=_/+\\-]/g, "");
    });

    const codigoField = document.getElementById("codigo-barras");
    codigoField.addEventListener("input", function () {
      this.value = this.value.replace(/[^0-9]/g, "");
    });

    const qtdField = document.getElementById("qtd");
    qtdField.addEventListener("input", function () {
      this.value = this.value.replace(/[^0-9]/g, "");
    });

    const classifField = document.getElementById("classif");
    classifField.addEventListener("input", function () {
      this.value = this.value.replace(/[0-9´~'!@#$%¨^&*(),.?":{}|<>[\];=_/+\\-]/g, "");
    });

    function hideSuccessMessage(message) {
      var successMessage = document.getElementById("success-cadastro-message");
      successMessage.innerText = message;
      successMessage.style.display = "block";

      setTimeout(function () {
        successMessage.style.display = "none";
      }, 4000);
    }
    var successMessage = document.getElementById("success-cadastro-message");
    if (successMessage) {
      var message = successMessage.innerText;
      hideSuccessMessage(message);
    }

    $(document).ready(function () {
      // Evento 'input' é acionado quando o usuário digita em um dos campos de filtro
      $('.filtro-nome, .filtro-codigo-barras, .filtro-classif, .filtro-qtd').on('input', function () {
        // Chamada para a função de atualização da lista de colaboradores
        atualizarListaEstoque();
      });

      function atualizarListaEstoque() {
        // Captura os valores dos campos de filtro
        var filtroNome = $('.filtro-nome').val().toLowerCase();
        var filtroQtd = $('.filtro-qtd').val().toLowerCase();
        var filtroCodigoBarras = $('.filtro-codigo-barras').val().toLowerCase();
        var filtroClassif = $('.filtro-classif').val().toLowerCase();

        // Itera sobre cada linha da tabela de colaboradores
        $('.table tbody tr').each(function () {
          // Obtém os valores dos campos em cada linha
          var nome = $(this).find('td:nth-child(1)').text().toLowerCase();
          var qtd = $(this).find('td:nth-child(2)').text().toLowerCase();
          var cod = $(this).find('td:nth-child(3)').text().toLowerCase();
          var classif = $(this).find('td:nth-child(4)').text().toLowerCase();

          // Verifica se os valores correspondem aos filtros e exibe ou oculta a linha
          if ((filtroNome === '' || nome.indexOf(filtroNome) !== -1) &&
            (filtroCodigoBarras === '' || cod.indexOf(filtroCodigoBarras) !== -1) &&
            (filtroClassif === '' || classif.indexOf(filtroClassif) !== -1) &&
            (filtroQtd === '' || qtd.indexOf(filtroQtd) !== -1)) {
            $(this).show(); // Exibe a linha se corresponder aos filtros
          } else {
            $(this).hide(); // Oculta a linha se não corresponder aos filtros
          }
        });
      }
    });
  </script>
  {% endblock %}
</body>

</html>